name: Lint

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black autoflake ruff

    - name: Check formatting with black
      run: black --check .

    - name: Check for unused imports with autoflake
      run: autoflake --check --recursive --remove-all-unused-imports .

    - name: Run ruff linter
      run: ruff check .
